version: '2.2'
services:
  gpg:
    image: vladgh/gpg
    volumes:
      - $PWD:/app
    working_dir: /app
  encrypt-env-integration:
    extends: gpg
    command:
      - --batch
      - --yes
      - --passphrase=$ENV_PASSWORD
      - --output=env.integration.gpg
      - --symmetric
      - .env.integration
  decrypt-env-integration:
    extends: gpg
    command:
      - '--decrypt'
      - '--batch'
      - "--passphrase=$ENV_PASSWORD"
      - '--output=.env.integration'
      - env.integration.gpg
  encrypt-env:
    extends: gpg
    command:
      - --batch
      - --yes
      - --passphrase=$ENV_PASSWORD
      - --output=env.gpg
      - --symmetric
      - .env
  decrypt-env:
    extends: gpg
    command:
      - '--decrypt'
      - '--batch'
      - "--passphrase=$ENV_PASSWORD"
      - '--output=.env'
      - env.gpg
