version: '2.2'
services:
  ruby:
    build:
      context: .
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint: sh
    command:
      - "-c"
      - "not meant to be run with the stack"
  unit:
    extends: ruby
    entrypoint: rspec
    environment:
      LOAD_PATH: "/app/spec;/app/lib"
    command:
      - --tag
      - "~wip"
      - --fail-fast
