version: '2.2'
services:
  serverless:
    build:
      dockerfile: serverless.Dockerfile
      context: .
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
  terraform:
    image: hashicorp/terraform
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint: 
      - sh
      - ./scripts/deploy_infra.sh
  ruby:
    build:
      context: .
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint: sh
    command:
      - "-c"
      - "not meant to be run with the stack"
  unit:
    extends: ruby
    entrypoint: rspec
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
    command:
      - --tag
      - "~wip"
      - --fail-fast
      - --format
      - documentation
      - --pattern
      - /app/spec/unit/**/*_spec.rb
  integration:
    extends: ruby
    entrypoint: rspec
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
    command:
      - --tag
      - "~wip"
      - --fail-fast
      - --pattern
      - /app/spec/integration/**/*_spec.rb
  validate-serverless-infra:
    extends: terraform
    command:
      - plan
      - --input=false
  deploy-serverless-infra:
    extends: terraform
    command:
      - apply
      - --auto-approve=true
      - --input=false
  deploy-serverless:
    extends: serverless
    command:
      - deploy
