---
plugins: ${file(./serverless_plugins.yml):${self:provider.stage}}

service:
  name: slack-apis

frameworkVersion: '>=1.0.0'

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION, 'us-east-2'}
  memorySize: 256
  deploymentBucket:
    name: ${env:SERVERLESS_BUCKET_NAME}
  deploymentPrefix: serverless
  apiKeys:
    - default_key
  tracing:
    apiGateway: true

package:
  include:
    - lib/**
    - bin/**
    - vendor/**
  exclude:
    - scripts/**
    - secrets/**
    - infra/**
    - docker-compose.*
    - .terraform/**
    - spec/**
    - .env*

functions:
  auth:
    handler: bin/slack-api.begin_authentication
    description: Function that directs the user to start the Slack OAuth flow.
    timeout: 30
    environment:
      GEM_PATH: vendor/bundle
      SLACK_APP_CLIENT_ID: ${env:SLACK_APP_CLIENT_ID}
    events:
      - http: GET auth
        cors: true
        private: true
  callback:
    handler: bin/slack-api.handle_callback
    description: Function that receives Slack OAuth callbacks.
    timeout: 30
    environment:
      GEM_PATH: vendor/bundle
    events:
      - http: GET callback
        cors: true
  ping:
    handler: bin/slack-api.ping
    description: Healthiness endpoint for APIs.
    timeout: 30
    environment:
      GEM_PATH: vendor/bundle
    events:
      - http: GET ping
        cors: true

custom:
  stage: "${opt:stage, self:provider.stage}"
  production:
    customDomain:
      domainName: ${env:DOMAIN_PATH}.${env:DOMAIN_TLD}
      basePath: ''
      createRoute53Record: true
