---
plugins: ${file(./serverless_plugins.yml):${self:provider.stage}}

service:
  name: slack-apis

frameworkVersion: '>=1.0.0'

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION, 'us-east-2'}
  memorySize: 256
  deploymentBucket:
    name: ${env:SERVERLESS_BUCKET_NAME}
  deploymentPrefix: serverless
  apiKeys:
    - default_key
  tracing:
    apiGateway: true

package:
  include:
    - lib/**
    - bin/**
    - vendor/**
  exclude:
    - scripts/**
    - secrets/**
    - infra/**
    - docker-compose.*

functions:
  ping:
    handler: bin/slack-api.ping
    description: Healthiness endpoint for APIs.
    timeout: 30
    environment:
      GEM_PATH: vendor/bundle
      USE_AWS: true
      APP_AWS_ACCESS_KEY_ID: ${file(./secrets/app_account_ak)}
      APP_AWS_SECRET_ACCESS_KEY: ${file(./secrets/app_account_sk)}
    events:
      - http: GET ping
        cors: true

custom:
  stage: "${opt:stage, self:provider.stage}"
  production:
    customDomain:
      domainName: ${env:DOMAIN_PATH}.${env:DOMAIN_TLD}
      basePath: ''
      createRoute53Record: true
