---
service:
  name: slack-apis

frameworkVersion: '>=1.0.0'

provider:
  name: aws
  runtime: ruby2.5
  region: ${opt:region, 'us-east-2'}
  memorySize: 256
  deploymentBucket:
    name: ${env:SERVERLESS_BUCKET_NAME}
  deploymentPrefix: serverless

package:
  include:
    - lib/**
    - bin/**
    - vendor/**
  exclude:
    - scripts/**
    - secrets/**
    - infra/**
    - docker-compose.*

functions:
  ping:
    handler: lib/slack-api/health.ping
    description: Healthiness endpoint for APIs.
    timeout: 60
    environment:
      GEM_PATH: vendor/bundle
      USE_AWS: true
      APP_AWS_ACCESS_KEY_ID: ${env:APP_AWS_ACCESS_KEY_ID}
      APP_AWS_SECRET_ACCESS_KEY: ${env:APP_AWS_SECRET_ACCESS_KEY}
    events:
      - http: GET ping
