#!/usr/bin/env bash
ENVIRONMENT="${ENVIRONMENT:-test}"
set -e

docker-compose run --rm vendor
case "$ENVIRONMENT" in
  test)
    for stage in deploy-serverless-infra-test deploy-serverless-functions-test
    do
      docker-compose -f docker-compose.deploy.yml run --rm "$stage"
    done
    ;;
  production)
    for stage in deploy-serverless-infra deploy-serverless-domain deploy-serverless-functions
    do
      docker-compose -f docker-compose.deploy.yml run --rm "$stage"
    done
    ;;
  *)
    >&2 echo "ERROR: Invalid environment: $ENVIRONMENT"
    exit 1
    ;;
esac
